### ISSUE TITLE
listswf: fileOffset odr-violation

### ISSUE THREAD

**Issue by asarubbo** [libming/libming#56]
On 0.4.7 by default listswf has an odr-violation:

```
=================================================================
==20414==ERROR: AddressSanitizer: odr-violation (0x00000146f440):
  [1] size=4 'fileOffset' read.c:30:5
  [2] size=4 'fileOffset' listaction.c:29:5
These globals were registered at these points:
  [1]:
    #0 0x429cbd in __asan_register_globals /tmp/portage/sys-devel/llvm-3.9.0-r1/work/llvm-3.9.0.src/projects/compiler-rt/lib/asan/asan_globals.cc:309
    #1 0x59d9e8  (/usr/bin/listswf+0x59d9e8)

  [2]:
    #0 0x429cbd in __asan_register_globals /tmp/portage/sys-devel/llvm-3.9.0-r1/work/llvm-3.9.0.src/projects/compiler-rt/lib/asan/asan_globals.cc:309
    #1 0x7f9f331b85c8  (/usr/lib64/libming.so.1+0x6f5c8)

==20414==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'fileOffset' at read.c:30:5
==20414==ABORTING
```

**Comment by strk** [comment]
Can you please check against current master branch ? 6dff24bc2543c55f277662144d0cec97e4a6d0c1

**Comment by asarubbo** [comment]
The behaviour didn't change

I didn't mind check but since nothing was changed in read.c and listaction.c regarding this issue I'm wondering about the nature of the request....

**Comment by strk** [comment]
Nature of request: I've been distracted, recently came back to find many security fixes by @rbalint via #63 so was hoping he'd fixed these as well. If he didn't, are you up for a patch of your own ?

**Comment by strk** [comment]
I've no plan to work on ming any soon but I'm happy to review patches and apply them if someone provides  them
